"""empty message

Revision ID: 9231b82cf253
Revises: eb492b6c645a
Create Date: 2025-11-29 12:28:15.833727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9231b82cf253'
down_revision = 'eb492b6c645a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qrcode_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utilisateur', schema=None) as batch_op:
        batch_op.drop_column('qrcode_path')

    # ### end Alembic commands ###
