"""empty message

Revision ID: de62d2442996
Revises: 9231b82cf253
Create Date: 2025-12-11 15:30:21.337259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de62d2442996'
down_revision = '9231b82cf253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.alter_column('gestionnaire_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.alter_column('gestionnaire_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
