"""empty message

Revision ID: fe559f3bed54
Revises: 
Create Date: 2025-11-12 18:07:45.289296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe559f3bed54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moyen_de_paiement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('details', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('enregistrement_id', sa.String(length=255), nullable=False),
    sa.Column('nom_table', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utilisateur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uniq_key', sa.String(length=80), nullable=True),
    sa.Column('nom', sa.String(length=80), nullable=True),
    sa.Column('post_nom', sa.String(length=80), nullable=True),
    sa.Column('picture', sa.String(length=255), nullable=True),
    sa.Column('prenom', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('roles', postgresql.ARRAY(sa.String(length=80)), nullable=True),
    sa.Column('other_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('activate_at', sa.DateTime(), nullable=True),
    sa.Column('deactivate_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('administrateur_organisation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_ajout', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gestionnaire_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_affectation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locateur_utilisateur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organisation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('devise', sa.String(length=50), nullable=True),
    sa.Column('sign_devise', sa.String(length=50), nullable=True),
    sa.Column('proprietaire_id', sa.Integer(), nullable=True),
    sa.Column('administrateur_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['administrateur_id'], ['administrateur_organisation.id'], ),
    sa.ForeignKeyConstraint(['proprietaire_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('gestionnaire_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gestionnaire_id'], ['gestionnaire_site.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appartement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('surface', sa.Float(), nullable=True),
    sa.Column('nb_chambres', sa.Integer(), nullable=True),
    sa.Column('loyer_mensuel', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('contrat_de_bail',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('montant_loyer', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('duree_mois_garantie', sa.Integer(), nullable=True),
    sa.Column('appartement_id', sa.UUID(), nullable=False),
    sa.Column('locateur_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appartement_id'], ['appartement.id'], ),
    sa.ForeignKeyConstraint(['locateur_id'], ['locateur_utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paiement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date_paiement', sa.Date(), nullable=True),
    sa.Column('montant', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('contrat_id', sa.UUID(), nullable=False),
    sa.Column('moyen_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contrat_id'], ['contrat_de_bail.id'], ),
    sa.ForeignKeyConstraint(['moyen_id'], ['moyen_de_paiement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paiement')
    op.drop_table('contrat_de_bail')
    op.drop_table('appartement')
    op.drop_table('site')
    op.drop_table('organisation')
    op.drop_table('locateur_utilisateur')
    op.drop_table('gestionnaire_site')
    op.drop_table('administrateur_organisation')
    op.drop_table('utilisateur')
    op.drop_table('photo')
    op.drop_table('moyen_de_paiement')
    # ### end Alembic commands ###
